"""Speech engine configuration and safe placeholders.

This module centralizes STT/TTS configuration and provides small, safe
placeholders so the rest of the app can refer to audio/endpointing
settings without failing when Google APIs or binaries are not installed.
"""
import os
import logging
from typing import Optional

logger = logging.getLogger("agentlee.speech")

# Provider selection
STT_PROVIDER = os.getenv("AGENTLEE_STT_PROVIDER", "google_stt")
TTS_PROVIDER = os.getenv("AGENTLEE_TTS_PROVIDER", "google_tts")

# Endpointing (VAD) defaults (seconds)
MIN_ENDPOINT_DELAY = float(os.getenv("AGENTLEE_MIN_ENDPOINT_DELAY", "0.8"))
MAX_ENDPOINT_DELAY = float(os.getenv("AGENTLEE_MAX_ENDPOINT_DELAY", "6.0"))

# Correction window (seconds) as described in Nexus Protocol
AUTO_DISPATCH_DELAY = float(os.getenv("AGENTLEE_AUTO_DISPATCH_DELAY", "5.0"))


def generate_expressive_speech(text: str, voice: Optional[str] = None) -> str:
    """Return an SSML-wrapped string. This is a best-effort helper that
    safely formats text as SSML; it does not call any external API.
    """
    # Minimal SSML wrapper. Engineers should replace or extend this to
    # include prosody, breaks, and expressive markup generated by the model.
    safe_text = (text or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    ssml = f"<speak>{safe_text}</speak>"
    return ssml


import requests
def synthesize_ssml_to_audio(ssml: str, voice: str = "neutral", audio_format: str = "wav") -> bytes:
    # Call local /speak service
    base_url = os.getenv("AGENTLEE_TTS_URL", "http://localhost:8000")
    try:
        # Strip SSML tags naively; your existing code may already build SSML from plain text
        import re
        text = re.sub(r"<[^>]+>", "", ssml)
        resp = requests.post(f"{base_url}/speak", json={
            "text": text, "voice": voice, "format": audio_format, "visemes": True, "inline": True
        }, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        audio_path = data.get("audio_path")
        if audio_path and os.path.exists(audio_path):
            with open(audio_path, "rb") as f:
                return f.read()
    except Exception:
        pass
    return b""


def describe_config() -> dict:
    return {
        "stt_provider": STT_PROVIDER,
        "tts_provider": TTS_PROVIDER,
        "min_endpoint_delay": MIN_ENDPOINT_DELAY,
        "max_endpoint_delay": MAX_ENDPOINT_DELAY,
        "auto_dispatch_delay": AUTO_DISPATCH_DELAY,
    }
